#!/usr/bin/env bash
# Gate: Review — ensure review-coverage.json exists, is complete, and matches HEAD
# Produces: .quality/proof/review.json
# Phase: ship (push-time enforcement)
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── 1. Capture SDLC_MANAGED signal ────────────────────────────────────────────
# Use the presence of sdlc.config.json as the authoritative opt-in marker.
# (An earlier version tested .quality/ existence but that directory is created
# as a side effect of load-config.sh line 9, making the check unreliable once
# any gate has run. sdlc.config.json is only ever created by explicit opt-in.)
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")
if [ -f "$REPO_ROOT/sdlc.config.json" ]; then
  SDLC_MANAGED=true
else
  SDLC_MANAGED=false
fi

# shellcheck source=plugins/sdlc/scripts/load-config.sh
source "$SCRIPT_DIR/load-config.sh"

# Clear allow-tracking file from prior runs
mkdir -p "${PROOF_DIR:-.quality/proof}" && : >"${PROOF_DIR:-.quality/proof}/allow-tracking-review.jsonl"

SHA=$(git rev-parse HEAD 2>/dev/null || echo 'unknown')
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD)
BRANCH_ESC=$(printf '%s' "$BRANCH" | sed 's/\\/\\\\/g; s/"/\\"/g')
COVERAGE_FILE="$REPO_ROOT/.quality/proof/review-coverage.json"

# ─── Crash trap ──────────────────────────────────────────────────────────────
# Inline trap avoids shellcheck SC2329 false positive for trap-invoked functions.
# _rc is assigned and read inside the trap body below.
_rc=0
trap '_rc=$?; printf "{\n  \"gate\": \"review\",\n  \"sha\": \"%s\",\n  \"status\": \"fail\",\n  \"error\": \"script crashed with exit code %s\",\n  \"coverage_sha\": \"\",\n  \"coverage_status\": \"missing\",\n  \"incomplete_agents\": [],\n  \"bypassed_via\": null,\n  \"reason\": null,\n  \"timestamp\": \"%s\"\n}\n" "$SHA" "$_rc" "$TIMESTAMP" > "$PROOF_DIR/review.json"; cat "$PROOF_DIR/review.json"; echo "GATE FAILED: script crashed (exit $_rc) — run with bash -x to debug" >&2' ERR

# JSON-escape an arbitrary string for inclusion in a heredoc
# (env var must be set BEFORE python3, not after — positional args are not env)
_json_escape() {
  _ERR="$1" python3 -c "import json,os; print(json.dumps(os.environ['_ERR']))"
}

# ─── 1.5. CI skip ────────────────────────────────────────────────────────────
# review-coverage.json is generated by /sdlc:review on the author's workstation
# and lives under .quality/proof/ which is gitignored. CI environments can't
# produce this artifact, so enforcement in CI would always fail. The review
# gate is author-side pre-push enforcement; CI verifies committed code.
if [ "${CI:-}" = "true" ] || [ -n "${GITHUB_ACTIONS:-}" ]; then
  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "skip",
  "error": null,
  "coverage_sha": "",
  "coverage_status": "missing",
  "incomplete_agents": [],
  "bypassed_via": "ci_environment",
  "reason": "review gate is author-side only — review-coverage.json lives outside the repo",
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  exit 0
fi

# ─── 2. Not sdlc-managed → skip ────────────────────────────────────────────────
if [ "$SDLC_MANAGED" = "false" ]; then
  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "skip",
  "error": null,
  "coverage_sha": "",
  "coverage_status": "missing",
  "incomplete_agents": [],
  "bypassed_via": null,
  "reason": "not sdlc-managed (no sdlc.config.json)",
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  exit 0
fi

# ─── 3. Allow-list check ─────────────────────────────────────────────────────
if is_allowed "review" "branch=$BRANCH"; then
  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "skip",
  "error": null,
  "coverage_sha": "",
  "coverage_status": "missing",
  "incomplete_agents": [],
  "bypassed_via": "allow_list",
  "reason": "branch '$BRANCH_ESC' matched allow.review entry",
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  report_unused_allow_entries review
  exit 0
fi

# ─── 4. Missing review-coverage.json → fail ──────────────────────────────────
if [ ! -f "$COVERAGE_FILE" ]; then
  ERROR_MSG="no review coverage proof — run /sdlc:review before pushing"
  ERROR_JSON=$(_json_escape "$ERROR_MSG")

  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "fail",
  "error": $ERROR_JSON,
  "coverage_sha": "",
  "coverage_status": "missing",
  "incomplete_agents": [],
  "bypassed_via": null,
  "reason": null,
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  echo "$ERROR_MSG" >&2
  report_unused_allow_entries review
  exit 1
fi

# ─── 5. Parse review-coverage.json ───────────────────────────────────────────
# Write parsed fields to a temp file — avoids fragile shell field-splitting on
# the JSON array. Pass file path via env, never string-interpolate into python.
_PARSE_TMP=$(mktemp)
COVERAGE_FILE="$COVERAGE_FILE" python3 <<'PYEOF' >"$_PARSE_TMP" 2>/dev/null
import json, os, sys

path = os.environ['COVERAGE_FILE']
try:
    with open(path) as f:
        data = json.load(f)
except Exception:
    print("parse_error=true")
    sys.exit(0)

sha = data.get('sha', '')
status = data.get('status', '')
agents = data.get('agents', {})

# Derive incomplete_agents by iterating agents.<name>.remaining
incomplete = []
for name, info in agents.items():
    remaining = info.get('remaining', [])
    if isinstance(remaining, list) and len(remaining) > 0:
        incomplete.append(name)

print("parse_error=false")
print(f"coverage_sha={sha}")
print(f"coverage_status={status}")
total_remaining = sum(len(info.get('remaining', [])) for info in agents.values())
print(f"incomplete_json={json.dumps(sorted(incomplete))}")
print(f"total_remaining={total_remaining}")
print(f"incomplete_list={','.join(sorted(incomplete)) if incomplete else ''}")
PYEOF

# Check for parse error
if grep -q '^parse_error=true' "$_PARSE_TMP" 2>/dev/null || [ ! -s "$_PARSE_TMP" ]; then
  rm -f "$_PARSE_TMP"
  ERROR_MSG="Failed to parse review-coverage.json"
  ERROR_JSON=$(_json_escape "$ERROR_MSG")

  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "fail",
  "error": $ERROR_JSON,
  "coverage_sha": "",
  "coverage_status": "missing",
  "incomplete_agents": [],
  "bypassed_via": null,
  "reason": null,
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  echo "$ERROR_MSG" >&2
  report_unused_allow_entries review
  exit 1
fi

COVERAGE_SHA=$(grep '^coverage_sha=' "$_PARSE_TMP" | cut -d= -f2-)
COVERAGE_STATUS=$(grep '^coverage_status=' "$_PARSE_TMP" | cut -d= -f2-)
INCOMPLETE_AGENTS_JSON=$(grep '^incomplete_json=' "$_PARSE_TMP" | cut -d= -f2-)
TOTAL_REMAINING=$(grep '^total_remaining=' "$_PARSE_TMP" | cut -d= -f2-)
INCOMPLETE_LIST=$(grep '^incomplete_list=' "$_PARSE_TMP" | cut -d= -f2-)
rm -f "$_PARSE_TMP"

# ─── 6. Incomplete status → fail ─────────────────────────────────────────────
if [ "$COVERAGE_STATUS" != "complete" ]; then
  ERROR_MSG="review incomplete — ${TOTAL_REMAINING} remaining item(s) across agents: ${INCOMPLETE_LIST}"
  ERROR_JSON=$(_json_escape "$ERROR_MSG")

  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "fail",
  "error": $ERROR_JSON,
  "coverage_sha": "$COVERAGE_SHA",
  "coverage_status": "incomplete",
  "incomplete_agents": $INCOMPLETE_AGENTS_JSON,
  "bypassed_via": null,
  "reason": null,
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  echo "$ERROR_MSG" >&2
  report_unused_allow_entries review
  exit 1
fi

# ─── 7. Stale SHA → fail ─────────────────────────────────────────────────────
# Empty COVERAGE_SHA is itself a fail signal — we can't verify freshness when
# review-coverage.json omits the sha field, so we must not pass.
if [ "$COVERAGE_SHA" != "$SHA" ]; then
  ERROR_MSG="review was run at ${COVERAGE_SHA:-<missing>} but HEAD is now ${SHA} — re-run /sdlc:review"
  ERROR_JSON=$(_json_escape "$ERROR_MSG")

  trap - ERR
  cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "fail",
  "error": $ERROR_JSON,
  "coverage_sha": "$COVERAGE_SHA",
  "coverage_status": "complete",
  "incomplete_agents": [],
  "bypassed_via": null,
  "reason": null,
  "timestamp": "$TIMESTAMP"
}
ENDJSON
  cat "$PROOF_DIR/review.json"
  echo "$ERROR_MSG" >&2
  report_unused_allow_entries review
  exit 1
fi

# ─── 8. Pass ──────────────────────────────────────────────────────────────────
trap - ERR
cat >"$PROOF_DIR/review.json" <<ENDJSON
{
  "gate": "review",
  "sha": "$SHA",
  "status": "pass",
  "error": null,
  "coverage_sha": "$COVERAGE_SHA",
  "coverage_status": "complete",
  "incomplete_agents": [],
  "bypassed_via": null,
  "reason": null,
  "timestamp": "$TIMESTAMP"
}
ENDJSON
cat "$PROOF_DIR/review.json"
report_unused_allow_entries review
exit 0
